"use client";
import { motion } from "framer-motion";
import { Activity, ArrowUpRight, Bell, Blocks, Check, ChevronDown, Command, FileUp, Hexagon, Network, Plus, Search, ShieldCheck, Sparkles, TriangleAlert, WalletCards } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip } from "recharts";
import { useState } from "react";

const riskData=[{d:"Mon",v:54},{d:"Tue",v:57},{d:"Wed",v:53},{d:"Thu",v:64},{d:"Fri",v:61},{d:"Sat",v:72},{d:"Sun",v:68}];
const contracts=[
  ["MSA · Microsoft Azure","MSFT-2024-117","$2.4M","14 Sep 2026","Elevated"],
  ["Data Processing Addendum","DPA-2025-021","$680K","03 Oct 2026","Protected"],
  ["Global Logistics Framework","GLF-2023-098","$1.1M","28 Aug 2026","Action needed"]
];
function Status({children}:{children:string}) { const c=children==="Protected"?"bg-signal/10 text-signal border-signal/20":children==="Elevated"?"bg-violet/10 text-violet border-violet/20":"bg-danger/10 text-danger border-danger/20"; return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-1 text-[10px] font-bold ${c}`}><i className="h-1.5 w-1.5 rounded-full bg-current"/>{children}</span> }
export default function Home(){
 const [tab,setTab]=useState("Overview"); const [uploaded,setUploaded]=useState(false);
 return <main className="min-h-screen grid-bg"><div className="fixed inset-0 bg-[radial-gradient(ellipse_at_70%_0%,rgba(104,75,219,.14),transparent_37%),radial-gradient(ellipse_at_25%_35%,rgba(39,184,156,.09),transparent_32%)] pointer-events-none"/>
 <aside className="fixed inset-y-0 left-0 z-20 w-64 border-r border-line bg-[#090c12]/90 px-4 py-5 backdrop-blur-xl">
  <div className="mb-10 flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-signal to-violet shadow-glow"><Hexagon size={20} className="text-canvas"/></div><div><div className="text-sm font-bold tracking-tight">CHAINSCRIBE</div><div className="text-[9px] tracking-[.18em] text-signal">ENTERPRISE</div></div></div>
  <button className="mb-7 flex w-full items-center justify-between rounded-lg border border-line bg-white/[.03] px-3 py-2 text-xs text-muted"><span className="flex items-center gap-2"><Search size={14}/>Search</span><kbd className="rounded bg-white/5 px-1.5 py-0.5 text-[9px]">⌘ K</kbd></button>
  <div className="space-y-1">{[["Overview",Activity],["Contracts",WalletCards],["Obligation Graph",Network],["Risk Intelligence",TriangleAlert],["Audit Ledger",Blocks]].map(([x,I])=><button key={x as string} onClick={()=>setTab(x as string)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-xs transition ${tab===x?"bg-white/[.08] text-ink shadow-sm":"text-muted hover:bg-white/[.04] hover:text-ink"}`}><I size={16}/>{x as string}{x==="Risk Intelligence"&&<span className="ml-auto rounded bg-danger/15 px-1.5 py-0.5 text-[9px] text-danger">07</span>}</button>)}</div>
  <div className="absolute bottom-5 left-4 right-4 rounded-xl border border-line bg-white/[.025] p-3"><div className="mb-2 flex items-center justify-between text-[10px]"><span className="text-muted">Workspace health</span><span className="text-signal">92%</span></div><div className="h-1 overflow-hidden rounded bg-white/10"><div className="h-full w-[92%] bg-signal"/></div><div className="mt-3 flex items-center gap-2 text-[10px] text-muted"><div className="grid h-5 w-5 place-items-center rounded bg-violet/20 text-[8px] text-violet">GE</div>Galaxy Enterprises<ChevronDown size={12} className="ml-auto"/></div></div>
 </aside>
 <section className="relative ml-64 min-h-screen p-7"><header className="mb-8 flex items-center justify-between"><div><div className="eyebrow mb-2">Command Center / {tab}</div><h1 className="text-2xl font-semibold tracking-tight">Contract intelligence, <span className="text-signal">proven.</span></h1></div><div className="flex items-center gap-3"><button className="relative rounded-lg border border-line p-2 text-muted hover:text-ink"><Bell size={16}/><i className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-danger"/></button><button onClick={()=>setUploaded(true)} className="flex items-center gap-2 rounded-lg bg-ink px-3.5 py-2.5 text-xs font-bold text-canvas hover:bg-white"><FileUp size={15}/>Upload contract</button></div></header>
 {uploaded&&<motion.div initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} className="mb-5 flex items-center justify-between rounded-xl border border-signal/30 bg-signal/10 px-4 py-3 text-xs"><span className="flex items-center gap-2 text-signal"><Check size={16}/>Contract queued. Extraction graph is building in real time.</span><button onClick={()=>setUploaded(false)} className="text-muted">Dismiss</button></motion.div>}
 <div className="mb-6 grid grid-cols-4 gap-4">{[["$18.6M","Portfolio value","+12.4%","text-signal"],["14","Renewals in 90 days","3 need review","text-violet"],["68","Enterprise risk score","+4 vs last week","text-danger"],["92%","Compliance health","38 controls verified","text-signal"]].map(([v,l,s,c],i)=><motion.div key={l} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.06}} className="glass rounded-xl p-4 shadow-glow"><div className="eyebrow">{l}</div><div className="mt-3 flex items-end justify-between"><span className="text-2xl font-semibold tracking-tight">{v}</span><ArrowUpRight size={15} className={c}/></div><div className={`mt-2 text-[10px] ${c}`}>{s}</div></motion.div>)}</div>
 <div className="grid grid-cols-12 gap-5"><div className="col-span-8 space-y-5"><div className="glass overflow-hidden rounded-xl"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><div className="text-sm font-semibold">Obligation Graph</div><div className="mt-1 text-[11px] text-muted">Live relationship intelligence · MSFT-2024-117</div></div><button className="flex items-center gap-1 text-[11px] text-signal">Explore graph <ArrowUpRight size={13}/></button></div><div className="relative h-[300px] overflow-hidden"><div className="absolute inset-0 opacity-80" style={{backgroundImage:"radial-gradient(circle at 25% 40%, rgba(102,227,196,.18) 0 2px,transparent 3px), radial-gradient(circle at 69% 23%, rgba(148,118,255,.25) 0 3px,transparent 4px), radial-gradient(circle at 71% 74%, rgba(255,101,119,.25) 0 2px,transparent 3px)"}}/><svg className="absolute inset-0 h-full w-full"><path d="M165 150 C260 90 330 100 410 135 S550 70 610 85 M165 150 C270 210 355 220 470 190 S580 230 640 220 M410 135 C430 170 445 175 470 190" fill="none" stroke="rgba(130,144,165,.35)" strokeWidth="1" strokeDasharray="4 5"/></svg>{[["CONTRACT","left-[18%] top-[43%]","bg-signal text-canvas"],["SLA","left-[48%] top-[37%]","bg-violet text-white"],["VENDOR","left-[72%] top-[20%]","bg-[#28364d] text-ink"],["RISK 07","left-[75%] top-[66%]","bg-danger text-white"],["DEADLINE","left-[50%] top-[66%]","bg-[#28364d] text-ink"]].map(([t,p,c])=><motion.div whileHover={{scale:1.08}} key={t} className={`absolute ${p} ${c} rounded-full border border-white/15 px-3 py-2 text-[9px] font-bold tracking-wider shadow-lg`}>{t}</motion.div>)}</div><div className="flex gap-5 border-t border-line px-5 py-3 text-[10px] text-muted"><span className="flex items-center gap-1"><i className="h-2 w-2 rounded-full bg-signal"/>Verified entity</span><span className="flex items-center gap-1"><i className="h-2 w-2 rounded-full bg-violet"/>Obligation</span><span className="flex items-center gap-1"><i className="h-2 w-2 rounded-full bg-danger"/>Active risk</span></div></div>
 <div className="glass rounded-xl"><div className="flex items-center justify-between px-5 py-4"><div><div className="text-sm font-semibold">Contracts requiring attention</div><div className="mt-1 text-[11px] text-muted">Prioritized by renewal proximity & risk exposure</div></div><button className="rounded-md border border-line px-2.5 py-1.5 text-[10px] text-muted">View all</button></div><div className="divide-y divide-line">{contracts.map(c=><div key={c[1]} className="grid grid-cols-[1.5fr_.8fr_.7fr_.9fr_.9fr] items-center px-5 py-3.5 text-xs hover:bg-white/[.025]"><div><div className="font-medium">{c[0]}</div><div className="mt-1 text-[10px] text-muted">{c[1]}</div></div><span className="text-muted">{c[2]}</span><span className="text-muted">Renews</span><span className="text-muted">{c[3]}</span><Status>{c[4]}</Status></div>)}</div></div></div>
 <div className="col-span-4 space-y-5"><div className="glass rounded-xl p-5"><div className="flex items-start justify-between"><div><div className="text-sm font-semibold">Risk trajectory</div><div className="mt-1 text-[11px] text-muted">Last 7 days</div></div><span className="rounded bg-danger/10 px-2 py-1 text-[10px] text-danger">+8.2%</span></div><div className="mt-4 h-28"><ResponsiveContainer width="100%" height="100%"><AreaChart data={riskData}><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ff6577" stopOpacity=".4"/><stop offset="1" stopColor="#ff6577" stopOpacity="0"/></linearGradient></defs><Tooltip contentStyle={{background:'#0d1118',border:'1px solid #1d2635',fontSize:11}}/><Area type="monotone" dataKey="v" stroke="#ff6577" strokeWidth={2} fill="url(#g)"/></AreaChart></ResponsiveContainer></div><div className="mt-2 grid grid-cols-3 border-t border-line pt-4 text-center"><div><div className="text-sm font-semibold">07</div><div className="mt-1 text-[9px] text-muted">Critical</div></div><div className="border-x border-line"><div className="text-sm font-semibold">12</div><div className="mt-1 text-[9px] text-muted">Elevated</div></div><div><div className="text-sm font-semibold">31</div><div className="mt-1 text-[9px] text-muted">Monitored</div></div></div></div>
 <div className="glass rounded-xl p-5"><div className="mb-4 flex items-center justify-between"><div className="text-sm font-semibold">Proof of execution</div><ShieldCheck size={17} className="text-signal"/></div><div className="rounded-lg border border-signal/20 bg-signal/[.05] p-3"><div className="flex items-center gap-2 text-[11px] text-signal"><Blocks size={14}/>Polygon Amoy · Confirmed</div><div className="mt-3 break-all font-mono text-[10px] leading-relaxed text-muted">0x8f1a...e27b4c9d06ae1f6c1d43b</div></div><div className="mt-3 flex items-center justify-between text-[10px] text-muted"><span>Completion hash</span><span className="text-ink">4 min ago</span></div></div>
 <div className="rounded-xl border border-violet/25 bg-gradient-to-br from-violet/15 to-[#12121e] p-5"><div className="flex items-center gap-2 text-violet"><Sparkles size={15}/><span className="text-xs font-semibold">ChainScribe Copilot</span></div><p className="my-3 text-[11px] leading-relaxed text-muted">Ask about obligations, vendors, renewal risk, or compliance evidence.</p><button className="flex w-full items-center justify-between rounded-lg border border-white/10 bg-black/15 px-3 py-2.5 text-left text-[10px] text-muted">Ask a question <Command size={13}/></button></div></div></div>
 </section></main>
}
